In [3]:
import numpy as np 

[NumPy](http://www.numpy.org/) usage: 

- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generatio

In [4]:
#http://cs231n.github.io/python-numpy-tutorial/

In [5]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
print(a.shape)

(2, 3)


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
np_list = np.arange(10)
np_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.random.seed(2020)

inx_list = np.arange(len(np_list))
np.random.shuffle(np_list)

mixed_list = np_list[inx_list] 
mixed_list

array([2, 4, 9, 1, 5, 7, 6, 3, 8, 0])

## Log

In [16]:
log_value = np.log2( 100 )
np.exp2( log_value )

99.99999999999999

## Vector

In [17]:
np_list

array([2, 4, 9, 1, 5, 7, 6, 3, 8, 0])

In [18]:
print(type(np_list))

<class 'numpy.ndarray'>


In [19]:
np.array([x*2 for x in np_list])

array([ 4,  8, 18,  2, 10, 14, 12,  6, 16,  0])

In [20]:
np_list*2

array([ 4,  8, 18,  2, 10, 14, 12,  6, 16,  0])

## Ufunc

In [21]:
##np_list

array([2, 4, 9, 1, 5, 7, 6, 3, 8, 0])

In [22]:
np_list+np_list

array([ 4,  8, 18,  2, 10, 14, 12,  6, 16,  0])

## Filter

In [23]:
short_list = np.array([10, 5, 8])

In [24]:
short_list[ [2, 0, 1] ] #indexes 

array([ 8, 10,  5])

In [25]:
short_list[ [True, False, True] ]

array([10,  8])

In [26]:
short_list == 10 #where is 10

array([ True, False, False])

In [27]:
short_list[ short_list == 8 ] # only 8

array([8])

In [30]:
# normally [x*2 for x in my_list if x % 2 == 0]
np_list[ np_list % 2 == 0 ] * 2

array([ 4,  8, 12, 16,  0])

In [31]:
np_list

array([2, 4, 9, 1, 5, 7, 6, 3, 8, 0])

In [29]:
my_filter = my_list % 2 == 0
my_list[ my_filter ] * 2

array([ 0,  4,  8, 12, 16])

In [32]:
np_list[ (np_list < 3) | (np_list > 6) ]

array([2, 9, 1, 7, 8, 0])

In [ ]:
#exp ( log(x) )

## range()

In [66]:
range(5)

range(0, 5)

In [67]:
for i in range(5):
    print(i)

0
1
2
3
4


In [68]:
list(range(5))

[0, 1, 2, 3, 4]

## list comprehension

In [69]:
x = [1,2,3,4]

In [70]:
out = []
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


In [71]:
[item**2 for item in x]

[1, 4, 9, 16]

## functions

In [72]:
def my_func(param1='default'):
    """
    Docstring goes here.
    """
    print(param1)

In [73]:
my_func

<function __main__.my_func>

In [74]:
my_func()

default


In [75]:
my_func('new param')

new param


In [76]:
my_func(param1='new param')

new param


In [77]:
def square(x):
    return x**2

In [78]:
out = square(2)

In [79]:
print(out)

4


## lambda expressions

In [80]:
def times2(var):
    return var*2

In [81]:
times2(2)

4

In [82]:
lambda var: var*2

<function __main__.<lambda>>

## map and filter

In [83]:
seq = [1,2,3,4,5]

In [84]:
map(times2,seq)

In [85]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [86]:
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [87]:
filter(lambda item: item%2 == 0,seq)

In [88]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

## methods

In [111]:
st = 'hello my name is Sam'

In [112]:
st.lower()

'hello my name is sam'

In [113]:
st.upper()

'HELLO MY NAME IS SAM'

In [103]:
st.split()

['hello', 'my', 'name', 'is', 'Sam']

In [104]:
tweet = 'Go Sports! #Sports'

In [106]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [107]:
tweet.split('#')[1]

'Sports'

In [92]:
d

{'key1': 'item1', 'key2': 'item2'}

In [93]:
d.keys()

dict_keys(['key2', 'key1'])

In [94]:
d.items()

dict_items([('key2', 'item2'), ('key1', 'item1')])

In [95]:
lst = [1,2,3]

In [96]:
lst.pop()

3

In [108]:
lst

[1, 2]

In [109]:
'x' in [1,2,3]

False

In [110]:
'x' in ['x','y','z']

True